"""Observability for the agent. Lets us see what the agent saw, why it
decided what it did, and what happened next — without instrumenting every
worker by hand.

Two implementations:

  - `NullTraceWriter` (default): zero-cost no-op. Production uses this.
  - `FilesystemTraceWriter`: dev/eval — writes JSONL + screenshots + LLM
    I/O dumps to a per-run directory, plus a markdown report.

Wire-in points:

  - Orchestrator calls `record_orchestrator_turn(...)` after each decision.
  - PageReader calls `record_page_reader_turn(...)` per sub-loop iteration.
  - Both call `record_llm_call(...)` for every LLM invocation.
  - Both call `record_screenshot(...)` at meaningful visual moments.

The writer is passed through worker constructors / orchestrator state so
nothing in the call path has to know which implementation is active.
"""

from __future__ import annotations

import json
import logging
import time
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public ABC
# ---------------------------------------------------------------------------


class TraceWriter(ABC):
    """Per-run observability sink. One instance per agent run."""

    @abstractmethod
    def record_orchestrator_turn(
        self,
        *,
        turn: int,
        prompt: list[dict[str, Any]],
        response_content: str | None,
        decision_summary: str,
        worker_chosen: str,
        forced: bool = False,
    ) -> None:
        ...

    @abstractmethod
    def record_page_reader_turn(
        self,
        *,
        orchestrator_turn: int,
        sub_turn: int,
        url: str,
        snapshot_text: str,
        element_map_size: int,
        prompt: list[dict[str, Any]],
        response_content: str | None,
        action_summary: str,
        result_summary: str,
    ) -> None:
        ...

    @abstractmethod
    def record_screenshot(
        self,
        *,
        orchestrator_turn: int,
        sub_turn: int | None,
        label: str,
        png_bytes: bytes,
    ) -> None:
        ...

    @abstractmethod
    def record_error(
        self,
        *,
        orchestrator_turn: int,
        worker: str,
        error: str,
    ) -> None:
        ...

    @abstractmethod
    def finalize(self) -> None:
        """Called once at run end. Writes summary report, closes files."""
        ...


# ---------------------------------------------------------------------------
# Null impl (default, production)
# ---------------------------------------------------------------------------


class NullTraceWriter(TraceWriter):
    """No-op trace writer. Zero overhead. Used in production by default."""

    def record_orchestrator_turn(self, **_: Any) -> None:
        pass

    def record_page_reader_turn(self, **_: Any) -> None:
        pass

    def record_screenshot(self, **_: Any) -> None:
        pass

    def record_error(self, **_: Any) -> None:
        pass

    def finalize(self) -> None:
        pass


# ---------------------------------------------------------------------------
# Filesystem impl (dev / spike)
# ---------------------------------------------------------------------------


class FilesystemTraceWriter(TraceWriter):
    """Writes structured traces to disk. One directory per run.

    Layout:
      <root>/
        trace.jsonl              — one structured line per recorded event
        prompts/turn_<N>.json    — full LLM prompt per orchestrator turn
        responses/turn_<N>.json  — full LLM response per orchestrator turn
        prompts/turn_<N>_sub_<K>.json — PageReader prompts (one per sub-turn)
        responses/turn_<N>_sub_<K>.json
        snapshots/turn_<N>_sub_<K>.txt — page snapshot text the agent saw
        screenshots/turn_<N>_sub_<K>_<label>.png
        report.md                — generated by finalize() — human-readable summary
    """

    def __init__(self, root: Path | str, run_label: str | None = None) -> None:
        self._root = Path(root)
        self._root.mkdir(parents=True, exist_ok=True)
        (self._root / "prompts").mkdir(exist_ok=True)
        (self._root / "responses").mkdir(exist_ok=True)
        (self._root / "snapshots").mkdir(exist_ok=True)
        (self._root / "screenshots").mkdir(exist_ok=True)
        self._trace_path = self._root / "trace.jsonl"
        self._events: list[dict[str, Any]] = []  # in-memory mirror for the report
        self._started_at = datetime.now(timezone.utc).isoformat()
        self._run_label = run_label or self._root.name
        self._t0 = time.monotonic()

    # ------------------------------------------------------------------ writes

    def record_orchestrator_turn(
        self,
        *,
        turn: int,
        prompt: list[dict[str, Any]],
        response_content: str | None,
        decision_summary: str,
        worker_chosen: str,
        forced: bool = False,
    ) -> None:
        self._write_file(f"prompts/turn_{turn:02d}.json", prompt)
        self._write_file(
            f"responses/turn_{turn:02d}.json", {"content": response_content},
        )
        event = {
            "kind": "orchestrator_turn",
            "ts_offset_s": round(time.monotonic() - self._t0, 3),
            "turn": turn,
            "decision_summary": decision_summary,
            "worker_chosen": worker_chosen,
            "forced": forced,
        }
        self._events.append(event)
        self._append_trace(event)

    def record_page_reader_turn(
        self,
        *,
        orchestrator_turn: int,
        sub_turn: int,
        url: str,
        snapshot_text: str,
        element_map_size: int,
        prompt: list[dict[str, Any]],
        response_content: str | None,
        action_summary: str,
        result_summary: str,
    ) -> None:
        prefix = f"turn_{orchestrator_turn:02d}_sub_{sub_turn:02d}"
        try:
            (self._root / "snapshots" / f"{prefix}.txt").write_text(snapshot_text)
        except Exception as exc:
            logger.warning("trace: snapshot write failed: %s", exc)
        self._write_file(f"prompts/{prefix}.json", prompt)
        self._write_file(f"responses/{prefix}.json", {"content": response_content})
        event = {
            "kind": "page_reader_turn",
            "ts_offset_s": round(time.monotonic() - self._t0, 3),
            "orchestrator_turn": orchestrator_turn,
            "sub_turn": sub_turn,
            "url": url,
            "element_map_size": element_map_size,
            "snapshot_chars": len(snapshot_text),
            "action_summary": action_summary,
            "result_summary": result_summary,
        }
        self._events.append(event)
        self._append_trace(event)

    def record_screenshot(
        self,
        *,
        orchestrator_turn: int,
        sub_turn: int | None,
        label: str,
        png_bytes: bytes,
    ) -> None:
        if sub_turn is None:
            fname = f"turn_{orchestrator_turn:02d}_{label}.png"
        else:
            fname = f"turn_{orchestrator_turn:02d}_sub_{sub_turn:02d}_{label}.png"
        try:
            (self._root / "screenshots" / fname).write_bytes(png_bytes)
        except Exception as exc:
            logger.warning("trace: screenshot write failed: %s", exc)
        event = {
            "kind": "screenshot",
            "ts_offset_s": round(time.monotonic() - self._t0, 3),
            "orchestrator_turn": orchestrator_turn,
            "sub_turn": sub_turn,
            "label": label,
            "path": f"screenshots/{fname}",
        }
        self._events.append(event)
        self._append_trace(event)

    def record_error(
        self,
        *,
        orchestrator_turn: int,
        worker: str,
        error: str,
    ) -> None:
        event = {
            "kind": "error",
            "ts_offset_s": round(time.monotonic() - self._t0, 3),
            "orchestrator_turn": orchestrator_turn,
            "worker": worker,
            "error": error,
        }
        self._events.append(event)
        self._append_trace(event)

    # ----------------------------------------------------------------- helpers

    def _append_trace(self, event: dict[str, Any]) -> None:
        try:
            with self._trace_path.open("a") as f:
                f.write(json.dumps(event) + "\n")
        except Exception as exc:
            logger.warning("trace: jsonl write failed: %s", exc)

    def _write_file(self, rel: str, data: Any) -> None:
        try:
            (self._root / rel).write_text(
                json.dumps(data, indent=2, default=str),
            )
        except Exception as exc:
            logger.warning("trace: file write failed (%s): %s", rel, exc)

    # ----------------------------------------------------------------- report

    def finalize(self) -> None:
        try:
            self._write_report()
        except Exception:
            logger.exception("trace: report generation failed")

    def _write_report(self) -> None:
        lines: list[str] = []
        lines.append(f"# Agent run trace — `{self._run_label}`")
        lines.append("")
        lines.append(f"Started: {self._started_at}")
        lines.append(f"Events: {len(self._events)}")
        lines.append("")

        # Bucket events by orchestrator turn
        from collections import defaultdict
        by_turn: dict[int, list[dict[str, Any]]] = defaultdict(list)
        for e in self._events:
            t = e.get("turn") if e["kind"] == "orchestrator_turn" else e.get("orchestrator_turn", -1)
            by_turn[t].append(e)

        for turn in sorted(by_turn):
            if turn < 0:
                continue
            evs = by_turn[turn]
            orch = next((e for e in evs if e["kind"] == "orchestrator_turn"), None)
            lines.append(f"## Turn {turn}")
            if orch:
                forced_tag = " 🛑 FORCED" if orch.get("forced") else ""
                lines.append(
                    f"**Worker:** `{orch['worker_chosen']}`{forced_tag}  "
                    f"  **+{orch['ts_offset_s']:.1f}s**"
                )
                lines.append(f"**Decision:** {orch['decision_summary']}")
                lines.append(
                    f"_Prompt: [turn_{turn:02d}.json](prompts/turn_{turn:02d}.json) · "
                    f"Response: [turn_{turn:02d}.json](responses/turn_{turn:02d}.json)_"
                )
                lines.append("")
            sub_events = [e for e in evs if e["kind"] == "page_reader_turn"]
            if sub_events:
                lines.append("### PageReader sub-trace")
                for s in sub_events:
                    sub = s.get("sub_turn", -1)
                    url = s.get("url", "")
                    action = s.get("action_summary", "")
                    result = s.get("result_summary", "")
                    chars = s.get("snapshot_chars", 0)
                    elems = s.get("element_map_size", 0)
                    lines.append(
                        f"- **sub {sub}** `{url[:80]}` "
                        f"({chars} chars, {elems} elems)  \n"
                        f"  Action: `{action}`  \n"
                        f"  Result: {result[:140]}  \n"
                        f"  [snapshot](snapshots/turn_{turn:02d}_sub_{sub:02d}.txt) · "
                        f"[prompt](prompts/turn_{turn:02d}_sub_{sub:02d}.json) · "
                        f"[response](responses/turn_{turn:02d}_sub_{sub:02d}.json)"
                    )
            shots = [e for e in evs if e["kind"] == "screenshot"]
            if shots:
                lines.append("")
                lines.append("### Screenshots")
                for shot in shots:
                    lines.append(f"- ![{shot['label']}]({shot['path']})")
            errs = [e for e in evs if e["kind"] == "error"]
            for err in errs:
                lines.append(f"> ❌ **ERROR** ({err['worker']}): {err['error']}")
            lines.append("")

        (self._root / "report.md").write_text("\n".join(lines))
